# .readthedocs.yaml
# Archivo de configuración para Read the Docs - Versión corregida y completa para accim

# Requerido
version: 2

# Define el entorno de construcción, respetando python_requires='<3.10'
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Especifica la ruta correcta a tu archivo de configuración de Sphinx
sphinx:
  configuration: docs/source/conf.py

# Construye la documentación en formatos adicionales (mantenido de tu config original)
formats:
  - pdf
  - epub

# Define cómo instalar tu paquete y sus dependencias
python:
  install:
    # 1. Instala tu paquete 'accim' para que Sphinx pueda importarlo
    - method: pip
      path: .
      # 2. Desactiva la ejecución del script post-instalación que modificaría archivos de EnergyPlus
      #extra_requirements:
      #  - "no-idd-mod"
        
    # 3. Instala las dependencias de Sphinx y de accim desde un archivo dedicado
    - requirements: docs/requirements.txt